name: "List Make Prerequisites Action"
description: "List all prerequisites of a Makefile target"
author: "Luca Colagrande"

inputs:
  target:
    description: "Target to list prerequisites for"
    required: true
  working-directory:
    description: "Working directory to run Make in"
    required: false
    default: '.'
  flags:
    description: "Additional flags to pass to list-make-prerequisites.py"
    required: false
    default: ''

outputs:
  hash:
    description: "Hash of all prerequisite file contents"
    value: ${{ steps.list-make-prerequisites.outputs.hash }}
  prerequisites:
    description: "List of all prerequisite files"
    value: ${{ steps.list-make-prerequisites.outputs.prerequisites }}

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: python -m pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
    - name: List Make Prerequisites
      id: list-make-prerequisites
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        hash=$(${GITHUB_ACTION_PATH}/list-make-prerequisites.py ${{ inputs.target }} ${{ inputs.flags }} --hash 2>/dev/null)
        prerequisites=$(${GITHUB_ACTION_PATH}/list-make-prerequisites.py ${{ inputs.target }} ${{ inputs.flags }} 2>/dev/null)
        echo "hash=$hash" >> $GITHUB_OUTPUT
        echo "prerequisites=$prerequisites" >> $GITHUB_OUTPUT
